//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/UIControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UIControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UIControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UIControls"",
    ""maps"": [
        {
            ""name"": ""UINavigation"",
            ""id"": ""0dc9d6b1-ec6a-4abb-b13f-8bc11d03b835"",
            ""actions"": [
                {
                    ""name"": ""Right Next"",
                    ""type"": ""Button"",
                    ""id"": ""dd4e1e94-eab3-43e6-9bbc-8b8146135b68"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left Next"",
                    ""type"": ""Button"",
                    ""id"": ""dfa6cc85-885a-4b9f-b3d2-51625316953e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""c475c375-467d-42da-bec9-a15512956798"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""46e09918-9f2f-4e78-aaa2-e6e1603da04e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right Next"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""102dc84f-9f89-4cdf-b0bc-5de0f9fe0f5e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left Next"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70ff8b08-0f33-4401-a113-393a338790b9"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // UINavigation
        m_UINavigation = asset.FindActionMap("UINavigation", throwIfNotFound: true);
        m_UINavigation_RightNext = m_UINavigation.FindAction("Right Next", throwIfNotFound: true);
        m_UINavigation_LeftNext = m_UINavigation.FindAction("Left Next", throwIfNotFound: true);
        m_UINavigation_Select = m_UINavigation.FindAction("Select", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // UINavigation
    private readonly InputActionMap m_UINavigation;
    private List<IUINavigationActions> m_UINavigationActionsCallbackInterfaces = new List<IUINavigationActions>();
    private readonly InputAction m_UINavigation_RightNext;
    private readonly InputAction m_UINavigation_LeftNext;
    private readonly InputAction m_UINavigation_Select;
    public struct UINavigationActions
    {
        private @UIControls m_Wrapper;
        public UINavigationActions(@UIControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @RightNext => m_Wrapper.m_UINavigation_RightNext;
        public InputAction @LeftNext => m_Wrapper.m_UINavigation_LeftNext;
        public InputAction @Select => m_Wrapper.m_UINavigation_Select;
        public InputActionMap Get() { return m_Wrapper.m_UINavigation; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UINavigationActions set) { return set.Get(); }
        public void AddCallbacks(IUINavigationActions instance)
        {
            if (instance == null || m_Wrapper.m_UINavigationActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UINavigationActionsCallbackInterfaces.Add(instance);
            @RightNext.started += instance.OnRightNext;
            @RightNext.performed += instance.OnRightNext;
            @RightNext.canceled += instance.OnRightNext;
            @LeftNext.started += instance.OnLeftNext;
            @LeftNext.performed += instance.OnLeftNext;
            @LeftNext.canceled += instance.OnLeftNext;
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
        }

        private void UnregisterCallbacks(IUINavigationActions instance)
        {
            @RightNext.started -= instance.OnRightNext;
            @RightNext.performed -= instance.OnRightNext;
            @RightNext.canceled -= instance.OnRightNext;
            @LeftNext.started -= instance.OnLeftNext;
            @LeftNext.performed -= instance.OnLeftNext;
            @LeftNext.canceled -= instance.OnLeftNext;
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
        }

        public void RemoveCallbacks(IUINavigationActions instance)
        {
            if (m_Wrapper.m_UINavigationActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUINavigationActions instance)
        {
            foreach (var item in m_Wrapper.m_UINavigationActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UINavigationActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UINavigationActions @UINavigation => new UINavigationActions(this);
    public interface IUINavigationActions
    {
        void OnRightNext(InputAction.CallbackContext context);
        void OnLeftNext(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
    }
}
